{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: ClusterRole
metadata:
  labels: {{ include "external-ips.labels" . | indent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "external-ips.fullname" . }}
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - services
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
{{- end -}}
