{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: ClusterRoleBinding
metadata:
  labels: {{ include "external-ips.labels" . | indent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "external-ips.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "external-ips.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "external-ips.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
