apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "external-ips.labels" . | indent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "external-ips.fullname" . }}
spec:
  selector:
    matchLabels: {{ include "external-ips.labels" . | indent 6 }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
    {{- end }}
      labels: {{ include "external-ips.labels" . | indent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $sec := .Values.image.pullSecrets }}
        - name: {{$sec | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      containers:
        - name: {{ template "external-ips.name" . }}
          image: "{{.Values.image.name}}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
          {{- if .Values.logLevel }}
            - --log-level={{ .Values.logLevel }}
          {{- end }}
          {{- range .Values.domainFilters }}
            - --domain-filter={{ . }}
          {{- end }}
            - --policy={{ .Values.policy }}
            - --provider={{ .Values.provider }}
            - --registry={{ .Values.registry }}
          {{- if .Values.txtOwnerId }}
            - --txt-owner-id={{ .Values.txtOwnerId }}
          {{- end }}
          {{- if .Values.txtPrefix }}
            - --txt-prefix={{ .Values.txtPrefix }}
          {{- end }}
          {{- if .Values.annotationFilter }}
            - --annotation-filter={{ .Values.annotationFilter }}
          {{- end }}
          {{- range .Values.sources }}
            - --source={{ . }}
          {{- end }}
          {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}
          {{- if .Values.aws.zoneType }}
            - --aws-zone-type={{ .Values.aws.zoneType }}
          {{- end }}
          {{- if (and .Values.aws.secretKey .Values.aws.accessKey) }}
          - name: aws-credentials
            mountPath: /root/.aws
            readOnly: true
          {{- end }}
          env:
        {{- if eq .Values.provider "aws" }}
        {{- if .Values.aws.region }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.aws.region }}
        {{- end }}
        {{- end }}
        {{- $root := . -}}
        {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ template "external-ips.fullname" $root }}
                key: {{ $key }}
        {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7979
          ports:
            - containerPort: 7979
        {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
      volumes:
      {{- if (and .Values.aws.secretKey .Values.aws.accessKey) }}
      - name: aws-credentials
        secret:
          secretName: {{ template "external-ips.fullname" . }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "external-ips.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
