{{- if or (and .Values.aws.secretKey .Values.aws.accessKey) .Values.extraEnv -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "external-ips.labels" . | indent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "external-ips.fullname" . }}
type: Opaque
data:
{{- if eq .Values.provider "aws" }}
  credentials: {{ include "external-ips.aws-credentials" . | b64enc | quote }}
  config: {{ include "external-ips.aws-config" . | b64enc | quote }}
{{- end}}
{{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
